"""LLM translator (OpenAI-compatible API)."""

import hashlib
import json
from typing import Any, Callable, Dict, List, Optional, Tuple, cast

import json_repair
import openai

from videocaptioner.core.llm.client import LLMCredentials, get_llm_credentials
from videocaptioner.core.llm.owned_request import OwnedLLMRequest
from videocaptioner.core.llm.request_policy import validate_request_timeout
from videocaptioner.core.prompts import get_prompt
from videocaptioner.core.translate.base import BaseTranslator, SubtitleProcessData, logger
from videocaptioner.core.translate.types import TargetLanguage
from videocaptioner.core.utils.cache import generate_cache_key


class LLMTranslator(BaseTranslator):
    """LLM translator (OpenAI-compatible API)."""

    require_complete_result = True

    MAX_STEPS = 3
    RESPONSE_POLICY = "complete-llm-response-v1"
    # Max source characters sent when building the global context (head/middle/tail sampled beyond)
    CONTEXT_MAX_CHARS = 12000
    # Below this many cues no global context is built: a "whole-film brief" summarised
    # from a few lines has no value yet costs an extra LLM call (re-translating a selection).
    CONTEXT_MIN_SEGMENTS = 10

    def __init__(
        self,
        thread_num: int,
        batch_num: int,
        target_language: TargetLanguage,
        model: str,
        custom_prompt: str,
        is_reflect: bool,
        update_callback: Optional[Callable],
        request_timeout: int = 120,
        credentials: Optional[LLMCredentials] = None,
    ):
        self.request_timeout = validate_request_timeout(request_timeout)
        self._credentials = credentials if credentials is not None else get_llm_credentials()
        super().__init__(
            thread_num=thread_num,
            batch_num=batch_num,
            target_language=target_language,
            update_callback=update_callback,
        )

        self.model = model
        self.custom_prompt = custom_prompt
        self.is_reflect = is_reflect
        # Global context brief (topic/tone/glossary) built by _prepare before translating
        self.global_context = ""
        # Deterministic fingerprint of the full source text, used in the cache key (see _get_cache_key)
        self.source_signature = ""

    def _prepare(self, translate_data_list: List[SubtitleProcessData]) -> None:
        """Build the global context once so every parallel chunk shares it."""
        # The cache key needs a deterministic "same film" identity. global_context cannot be it:
        # it is generated by the LLM at temperature=1, differs every run and would miss forever.
        self.source_signature = hashlib.sha256(
            "\n".join(d.original_text for d in translate_data_list).encode("utf-8")
        ).hexdigest()[:16]

        if self.conversation_snapshot is not None and self.conversation_snapshot.context.enabled:
            self.global_context = ""
            return

        if len(translate_data_list) < self.CONTEXT_MIN_SEGMENTS:
            logger.debug(
                "只有 %d 条字幕，跳过全局上下文构建", len(translate_data_list)
            )
            self.global_context = ""
            return

        self.global_context = self._build_global_context(translate_data_list)

    def _build_global_context(
        self, translate_data_list: List[SubtitleProcessData]
    ) -> str:
        """Read the whole source text and produce a compact context brief (topic/tone/glossary).

        Calls the LLM once; returns an empty string on failure so translation
        continues without it.
        """
        if not translate_data_list:
            return ""

        full_text = "\n".join(d.original_text for d in translate_data_list)
        # Sample head/middle/tail of very long inputs to stay within the context window
        if len(full_text) > self.CONTEXT_MAX_CHARS:
            third = self.CONTEXT_MAX_CHARS // 3
            mid_start = (len(full_text) - third) // 2
            full_text = (
                full_text[:third]
                + "\n...\n"
                + full_text[mid_start : mid_start + third]
                + "\n...\n"
                + full_text[-third:]
            )

        prompt = get_prompt("translate/context", target_language=self.target_language)
        try:
            response = self._request(
                messages=[
                    {"role": "system", "content": prompt},
                    {"role": "user", "content": full_text},
                ],
            )
            context = response.choices[0].message.content.strip()
            logger.debug("Global translation brief prepared")
            return context
        except Exception as e:
            logger.warning(f"构建全局上下文失败，跳过（不影响翻译）: {e}")
            return ""

    def _translate_chunk(
        self, subtitle_chunk: List[SubtitleProcessData]
    ) -> List[SubtitleProcessData]:
        """Translate one chunk."""
        logger.debug(
            f"[+]正在翻译字幕: {subtitle_chunk[0].index} - {subtitle_chunk[-1].index}"
        )

        # Dict form for the API call
        subtitle_dict = {str(data.index): data.original_text for data in subtitle_chunk}

        # Prompt
        if self.is_reflect:
            prompt = get_prompt(
                "translate/reflect",
                target_language=self.target_language,
                custom_prompt=self.custom_prompt,
                global_context=self.global_context,
            )
        else:
            prompt = get_prompt(
                "translate/standard",
                target_language=self.target_language,
                custom_prompt=self.custom_prompt,
                global_context=self.global_context,
            )

        snapshot = self.conversation_snapshot
        if snapshot is not None:
            payload = snapshot.request_data(tuple(d.cue_id for d in subtitle_chunk))
            payload["output_keys"] = {str(d.index): d.cue_id for d in subtitle_chunk}
            prompt += "\n" + get_prompt("translate/conversation")
            # JSON escapes dialogue delimiters; this block is explicitly data, never instructions.
            prompt += "\nCONVERSATION_DATA_JSON:\n" + json.dumps(payload, ensure_ascii=False, separators=(",", ":"))

        try:
            # Agent loop: translate, validate, and ask for corrections
            result_dict = self._agent_loop(prompt, subtitle_dict)

            processed_result = self._extract_translations(result_dict)
            if set(processed_result) != set(subtitle_dict):
                raise ValueError("Malformed translation; every input cue requires a translation.")

            # Write results back into SubtitleProcessData
            for data in subtitle_chunk:
                data.translated_text = processed_result[str(data.index)]
            return subtitle_chunk
        except openai.RateLimitError as e:
            logger.error(f"OpenAI Rate Limit Error: {str(e)}")
            raise
        except openai.AuthenticationError as e:
            logger.error(f"OpenAI Authentication Error: {str(e)}")
            raise
        except openai.NotFoundError as e:
            logger.error(f"OpenAI NotFound Error: {str(e)}")
            raise
        except Exception as e:
            logger.error(f"LLM translation error: {e}")
            raise

    def _extract_translations(self, result_dict: Any) -> Dict[str, str]:
        """Extract translations from the LLM result, skipping malformed entries.

        Reflective mode extracts ``native_translation``. Malformed entries are
        left out so the caller rejects the incomplete batch before publication.
        """
        if not isinstance(result_dict, dict):
            return {}

        processed: Dict[str, str] = {}
        for key, value in result_dict.items():
            text = value
            if isinstance(value, dict):
                text = value.get("native_translation")
            if isinstance(text, (int, float)) and not isinstance(text, bool):
                text = str(text)
            if isinstance(text, str) and text.strip():
                processed[str(key)] = text
            else:
                logger.warning(
                    "Subtitle #%s has a malformed translation structure (%s)",
                    key,
                    type(value).__name__,
                )
        return processed

    def _agent_loop(
        self, system_prompt: str, subtitle_dict: Dict[str, str]
    ) -> Dict[str, str]:
        """Agent loop for translating one chunk."""
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": json.dumps(subtitle_dict, ensure_ascii=False)},
        ]
        # LLM feedback loop
        for _ in range(self.MAX_STEPS):
            if not self.is_running:
                raise RuntimeError("Translation cancelled.")
            response = self._request(messages)
            response_dict = json_repair.loads(
                response.choices[0].message.content.strip()
            )
            is_valid, error_message = self._validate_llm_response(
                response_dict, subtitle_dict
            )
            if is_valid:
                # _validate_llm_response already proved this is a str->str dict.
                return cast(Dict[str, str], response_dict)
            else:
                messages.append(
                    {
                        "role": "assistant",
                        "content": json.dumps(response_dict, ensure_ascii=False),
                    }
                )
                messages.append(
                    {
                        "role": "user",
                        "content": f"Error: {error_message}\n\nFix the errors above and output ONLY a valid JSON dictionary with ALL {len(subtitle_dict)} keys",
                    }
                )

        # Reject incomplete batches before source-text fallbacks can enter the success cache.
        if self.conversation_snapshot is not None and self.conversation_snapshot.context.enabled:
            raise ValueError("Malformed contextual translation; review required.")
        raise ValueError(f"Malformed translation after {self.MAX_STEPS} responses; review required.")

    def _request(self, messages):
        """Every translation request owns its socket and immutable job credentials."""
        return OwnedLLMRequest(self._credentials, self.request_timeout, lambda: not self.is_running)(
            messages=messages, model=self.model)

    def _validate_llm_response(
        self, response_dict: Any, subtitle_dict: Dict[str, str]
    ) -> Tuple[bool, str]:
        """Validate the LLM result (plain and reflective modes).

        Returns: (is_valid, error_feedback)
        """
        if not isinstance(response_dict, dict):
            return (
                False,
                f"Output must be a dict, got {type(response_dict).__name__}. Use format: {{'0': 'text', '1': 'text'}}",
            )

        expected_keys = set(subtitle_dict.keys())
        actual_keys = set(response_dict.keys())

        def sort_keys(keys):
            return sorted(keys, key=lambda x: int(x) if x.isdigit() else x)

        # Keys must match
        if expected_keys != actual_keys:
            missing = expected_keys - actual_keys
            extra = actual_keys - expected_keys
            error_parts = []

            if missing:
                error_parts.append(
                    f"Missing keys {sort_keys(missing)} - you must translate these items"
                )
            if extra:
                error_parts.append(
                    f"Extra keys {sort_keys(extra)} - these keys are not in input, remove them"
                )

            return (False, "; ".join(error_parts))

        # Reflective mode: check the nested structure
        if self.is_reflect:
            for key, value in response_dict.items():
                if not isinstance(value, dict):
                    return (
                        False,
                        f"Key '{key}': value must be a dict with 'native_translation' field. Got {type(value).__name__}.",
                    )

                if "native_translation" not in value:
                    available_keys = list(value.keys())
                    return (
                        False,
                        f"Key '{key}': missing 'native_translation' field. Found keys: {available_keys}. Must include 'native_translation'.",
                    )

        for value in response_dict.values():
            text = value.get("native_translation") if isinstance(value, dict) else value
            if not isinstance(text, str) or not text.strip():
                return False, "Each translation must be a nonempty string."

        return True, ""

    def _translate_chunk_single(
        self, subtitle_chunk: List[SubtitleProcessData]
    ) -> List[SubtitleProcessData]:
        """Single-entry translation mode."""
        single_prompt = get_prompt(
            "translate/single", target_language=self.target_language
        )

        for data in subtitle_chunk:
            try:
                response = self._request(
                    messages=[
                        {"role": "system", "content": single_prompt},
                        {"role": "user", "content": data.original_text},
                    ],
                )
                translated_text = response.choices[0].message.content.strip()
                data.translated_text = translated_text
            except Exception as e:
                logger.error(f"Single item translation failed {data.index}: {str(e)}")

        return subtitle_chunk

    def _get_cache_key(self, chunk: List[SubtitleProcessData]) -> str:
        """Build the cache key.

        Besides text/language/model it includes reflective mode, the custom
        prompt, the full-source fingerprint and whether global context is
        enabled, so changing any of them never hits a stale entry.

        source_signature is used rather than global_context itself: the latter
        is LLM-generated and would make the cache miss on every run
        (a generated brief must never determine the cache identity).
        """
        class_name = self.__class__.__name__
        chunk_key = generate_cache_key(chunk)
        lang = self.target_language.value
        model = self.model
        settings_sig = hashlib.md5(
            f"{self.custom_prompt}\n{self.source_signature}\n"
            f"{self.RESPONSE_POLICY}\n"
            f"conversation-request-v2\n{self.conversation_snapshot.fingerprint if self.conversation_snapshot else ''}"
            f"\n{self._credentials.base_url if self._credentials else ''}"
            .encode("utf-8")
        ).hexdigest()[:8]
        return (
            f"{class_name}:{chunk_key}:{lang}:{model}"
            f":reflect={int(self.is_reflect)}:{settings_sig}"
        )
