"""ASS subtitle renderer"""

import os
import re
import subprocess
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING, Callable, Optional, Tuple

from PIL import Image

from videocaptioner.config import CACHE_PATH, FONTS_PATH, RESOURCE_PATH
from videocaptioner.core.entities import SubtitleLayoutEnum
from videocaptioner.core.utils.logger import setup_logger
from videocaptioner.core.utils.subprocess_helper import child_environment

from .ass_utils import auto_wrap_ass_file

if TYPE_CHECKING:
    from videocaptioner.core.asr.asr_data import ASRData

logger = setup_logger("subtitle.ass")
ASS_TEMPLATE = """[Script Info]
; Script generated by VideoCaptioner
ScriptType: v4.00+
PlayResX: {video_width}
PlayResY: {video_height}

{style_str}

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
{dialogue}
"""


def _escape_filter_path(path: str | Path) -> str:
    """Escape a path embedded in a quoted FFmpeg filter option."""
    return str(path).replace("\\", "/").replace(":", r"\:").replace("'", r"\'")


def _check_cuda_available() -> bool:
    """Whether CUDA is available."""
    from videocaptioner.core.utils.video_utils import check_cuda_available
    return check_cuda_available()


def _scale_ass_style(style_str: str, scale_factor: float) -> str:
    """
    Scale the numeric fields of an ASS style.

    Args:
        style_str: original ASS style string (720p)
        scale_factor: scale factor

    Returns:
        Scaled ASS style string
    """
    if scale_factor == 1.0:
        return style_str

    lines = style_str.split("\n")
    scaled_lines = []

    for line in lines:
        if line.startswith("Style:"):
            parts = line.split(",")
            if len(parts) >= 23:
                # parts[2]: Fontsize
                parts[2] = str(int(float(parts[2]) * scale_factor))
                # parts[13]: Spacing
                parts[13] = str(float(parts[13]) * scale_factor)
                # parts[16]: Outline
                parts[16] = str(float(parts[16]) * scale_factor)
                # parts[21]: MarginV (vertical margin)
                parts[21] = str(int(float(parts[21]) * scale_factor))
                line = ",".join(parts)
        scaled_lines.append(line)

    return "\n".join(scaled_lines)


def render_ass_preview(
    style_str: str,
    preview_text: Tuple[str, Optional[str]],
    bg_image_path: str,
    width: Optional[int] = None,
    height: Optional[int] = None,
    reference_height: int = 720,
) -> str:
    """
    Render an ASS-style subtitle preview image.

    Args:
        style_str: ASS style string (with PlayResY)
        preview_text: (original, translation) tuple; translation may be None
        bg_image_path: background image path
        width: image width (None = read from bg_image_path)
        height: image height (None = read from bg_image_path)
        reference_height: reference height (fixed 720p)
    Returns:
        Path of the generated preview image
    """
    # Read the image size
    if width is None or height is None:
        bg_path = Path(bg_image_path)
        if bg_path.exists():
            with Image.open(bg_path) as img:
                actual_width, actual_height = img.size
                width = width or actual_width
                height = height or actual_height
        else:
            width = width or 1920
            height = height or 1080

    original_text, translate_text = preview_text

    # Build the dialogue lines
    if translate_text:
        dialogue = [
            f"Dialogue: 0,0:00:00.00,0:00:01.00,Secondary,,0,0,0,,{translate_text}",
            f"Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,{original_text}",
        ]
    else:
        dialogue = [
            f"Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,{original_text}"
        ]

    # Generate the ASS content
    ass_content = ASS_TEMPLATE.format(
        style_str=style_str,
        dialogue=os.linesep.join(dialogue),
        video_width=width,
        video_height=height,
    )

    # Scale the style from the reference height to the image height
    scale_factor = height / reference_height
    style_str = _scale_ass_style(style_str, scale_factor)

    # Regenerate the ASS content with the scaled style
    ass_content = ASS_TEMPLATE.format(
        style_str=style_str,
        dialogue=os.linesep.join(dialogue),
        video_width=width,
        video_height=height,
    )

    # Keep runtime temp files beside the app data/cache instead of the OS drive.
    CACHE_PATH.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".ass",
        delete=False,
        encoding="utf-8",
        dir=CACHE_PATH,
    ) as f:
        f.write(ass_content)
        temp_ass_path = f.name

    processed_ass = temp_ass_path
    try:
        # Automatic line wrapping
        processed_ass = auto_wrap_ass_file(temp_ass_path)

        # Make sure a background image exists
        bg_path_obj = Path(bg_image_path)
        if not bg_path_obj.exists():
            # Fall back to a black background
            default_bg = RESOURCE_PATH / "assets" / "default_bg.png"
            if not default_bg.exists():
                default_bg.parent.mkdir(parents=True, exist_ok=True)
                # Generate the black background
                subprocess.run(
                    [
                        "ffmpeg",
                        "-f",
                        "lavfi",
                        "-i",
                        f"color=c=black:s={width}x{height}",
                        "-frames:v",
                        "1",
                        str(default_bg),
                    ], env=child_environment(),
                    capture_output=True,
                    creationflags=(
                        getattr(subprocess, "CREATE_NO_WINDOW", 0)
                        if os.name == "nt"
                        else 0
                    ),
                )
            bg_path_obj = default_bg

        # Render the preview
        output_path = CACHE_PATH / "ass_preview.png"
        output_path.parent.mkdir(parents=True, exist_ok=True)

        ass_file_escaped = _escape_filter_path(processed_ass)
        fonts_dir_escaped = _escape_filter_path(FONTS_PATH)

        cmd = [
            "ffmpeg",
            "-y",
            "-i",
            str(bg_path_obj),
            "-vf",
            f"ass='{ass_file_escaped}':fontsdir='{fonts_dir_escaped}'",
            "-frames:v",
            "1",
            str(output_path),
        ]

        result = subprocess.run(
            cmd, env=child_environment(),
            capture_output=True,
            creationflags=(
                getattr(subprocess, "CREATE_NO_WINDOW", 0) if os.name == "nt" else 0
            ),
        )

        if result.returncode != 0:
            logger.error(f"FFmpeg preview generation failed: {result.stderr}")

        return str(output_path)

    finally:
        # Clean up temp files
        Path(temp_ass_path).unlink(missing_ok=True)
        if processed_ass != temp_ass_path:
            Path(processed_ass).unlink(missing_ok=True)


def _get_video_resolution(video_path: str) -> Tuple[int, int]:
    """Video resolution."""
    result = subprocess.run(
        ["ffmpeg", "-i", video_path], env=child_environment(),
        capture_output=True,
        text=True,
        creationflags=(
            getattr(subprocess, "CREATE_NO_WINDOW", 0) if os.name == "nt" else 0
        ),
    )

    # Parse the resolution from ffmpeg output
    pattern = r"(\d{2,5})x(\d{2,5})"
    match = re.search(pattern, result.stderr)
    if match:
        return int(match.group(1)), int(match.group(2))
    return 1920, 1080  # Default to 1080p


def render_ass_video(
    video_path: str,
    asr_data: "ASRData",
    output_path: str,
    style_str: str,
    layout: SubtitleLayoutEnum,
    crf: int = 23,
    preset: str = "medium",
    progress_callback: Optional[Callable] = None,
    reference_height: int = 720,
) -> None:
    """
    Burn ASS-style subtitles into a video (hard subtitles).

    Args:
        video_path: input video path
        asr_data: subtitle data
        output_path: output video path
        style_str: ASS style string (with PlayResY)
        layout: subtitle layout
        crf: video quality (0-51, lower is better)
        preset: FFmpeg encoding preset
        progress_callback: progress callback (progress: str, message: str) -> None
        reference_height: reference height (fixed 720p)
    """
    # Check for empty subtitle data
    if not asr_data or not asr_data.segments:
        raise ValueError("Empty subtitle data, cannot render video")

    # Video resolution
    width, height = _get_video_resolution(video_path)

    # Scale the style to the video height
    scale_factor = height / reference_height
    style_str = _scale_ass_style(style_str, scale_factor)

    # Write a temp ASS file with the actual video resolution
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".ass", delete=False, encoding="utf-8"
    ) as temp_file:
        ass_content = asr_data.to_ass(
            style_str=style_str,
            layout=layout,
            save_path=None,
            video_width=width,
            video_height=height,
        )
        temp_file.write(ass_content)
        temp_ass_path = temp_file.name

    processed_subtitle = temp_ass_path
    try:
        # Automatic line wrapping
        processed_subtitle = auto_wrap_ass_file(temp_ass_path)

        # Escape the subtitle path
        subtitle_path_escaped = Path(processed_subtitle).as_posix().replace(":", r"\:")

        # Build the FFmpeg command
        vcodec = "libx264"
        if Path(output_path).suffix.lower() == ".webm":
            vcodec = "libvpx-vp9"
            logger.debug("WebM format, using libvpx-vp9")

        # Point the ass filter at the bundled fonts directory
        fonts_dir_escaped = FONTS_PATH.as_posix().replace(":", r"\:")

        # Always use the ass filter
        vf = f"ass='{subtitle_path_escaped}':fontsdir='{fonts_dir_escaped}'"

        # Check CUDA availability
        use_cuda = _check_cuda_available()
        cmd = ["ffmpeg"]
        if use_cuda:
            logger.debug("Using CUDA acceleration")
            cmd.extend(["-hwaccel", "cuda"])

        cmd.extend(
            [
                "-i",
                video_path,
                "-acodec",
                "copy",
                "-vcodec",
                vcodec,
                "-crf",
                str(crf),
                "-preset",
                preset,
                "-vf",
                vf,
                "-y",
                output_path,
            ]
        )

        cmd_str = subprocess.list2cmdline(cmd)
        logger.debug(f"FFmpeg ASS render cmd: {cmd_str}")

        # Run FFmpeg
        process = None
        try:
            process = subprocess.Popen(
                cmd, env=child_environment(),
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                encoding="utf-8",
                errors="replace",
                creationflags=(
                    getattr(subprocess, "CREATE_NO_WINDOW", 0) if os.name == "nt" else 0
                ),
            )

            # Read output live and report progress
            total_duration = None
            current_time = 0

            while True:
                output_line = process.stderr.readline()
                if not output_line or (process.poll() is not None):
                    break
                if not progress_callback:
                    continue

                # Parse the total duration
                if total_duration is None:
                    duration_match = re.search(
                        r"Duration: (\d{2}):(\d{2}):(\d{2}\.\d{2})", output_line
                    )
                    if duration_match:
                        h, m, s = map(float, duration_match.groups())
                        total_duration = h * 3600 + m * 60 + s

                # Parse the current position
                time_match = re.search(
                    r"time=(\d{2}):(\d{2}):(\d{2}\.\d{2})", output_line
                )
                if time_match:
                    h, m, s = map(float, time_match.groups())
                    current_time = h * 3600 + m * 60 + s

                # Compute the percentage
                if total_duration:
                    progress = (current_time / total_duration) * 100
                    progress_callback(f"{round(progress)}", "Đang ghép video")

            if progress_callback:
                progress_callback("100", "Hoàn tất ghép video")

            # Check the return code
            return_code = process.wait()
            if return_code != 0:
                error_info = process.stderr.read()
                logger.error("FFmpeg ASS rendering failed")
                logger.error(f"Return code: {return_code}")
                logger.error(f"Command: {cmd_str}")
                if error_info:
                    logger.error(f"Error output: {error_info}")
                raise Exception(f"FFmpeg Return code: {return_code}")

            logger.debug("ASS subtitle rendering complete")

        except subprocess.SubprocessError as e:
            logger.error("FFmpeg process error")
            logger.error(f"Error: {str(e)}")
            if process and process.poll() is None:
                process.kill()
            raise
        except Exception as e:
            logger.error(f"ASS subtitle rendering error: {str(e)}")
            if process and process.poll() is None:
                process.kill()
            raise

    finally:
        # Clean up temp files
        Path(temp_ass_path).unlink(missing_ok=True)
        if processed_subtitle != temp_ass_path:
            Path(processed_subtitle).unlink(missing_ok=True)
